source :rubygems

gem 'sinatra'
gem 'compass'
gem 'compass-susy-plugin'
gem 'haml'
gem 'sass'
gem 'shotgun'
gem 'heroku'
gem 'sinatra-flash'
gem 'ruby-debug19'
gem 'rest-client'
gem 'xml-simple'
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-transactions'
gem 'dm-timestamps'
gem 'dm-types'
gem 'dm-sqlite-adapter'
#gem 'dm-mysql-adapter'

